/**
 * USE CASE: Create User
 * Cria usuário com senha temporária
 */

const { v4: uuid } = require('uuid');
const User = require('../../../domain/entities/User');
const TemporaryPassword = require('../../../domain/value-objects/TemporaryPassword');
const AppError = require('../../../shared/utils/AppError');
const CacheService = require('../../../infrastructure/services/CacheService');
const logger = require('../../../infrastructure/config/logger');

class CreateUserUseCase {
  constructor(userRepository) {
    this.userRepository = userRepository;
  }

  async execute(createUserDTO) {
    // ✅ REGRA 1: Verificar se email já existe
    const emailInUse = await this.userRepository.isEmailInUse(createUserDTO.email);
    if (emailInUse) {
      throw new AppError('E-mail já está em uso.', 409);
    }

    // ✅ REGRA 2: Criar entidade User (valida automaticamente)
    const user = new User({
      id: uuid(),
      name: createUserDTO.name,
      email: createUserDTO.email,
      role: createUserDTO.role,
      cpf: createUserDTO.cpf,
      address_street: createUserDTO.address_street,
      address_number: createUserDTO.address_number,
      address_complement: createUserDTO.address_complement,
      address_neighborhood: createUserDTO.address_neighborhood,
      address_city: createUserDTO.address_city,
      address_state: createUserDTO.address_state,
      address_zip: createUserDTO.address_zip,
      is_active: true,
      must_change_password: true,
      is_active: true,
      last_login_at: null,
      created_at: new Date(),
      updated_at: new Date(),
    });

    // ✅ REGRA 3: Lógica de Senha (Manual vs Automática)
    // Se o Admin enviou uma senha no DTO, usamos ela. Caso contrário, geramos a temporária.
    let passwordToSave;
    let isTemporary = false;

    if (createUserDTO.password) {
      passwordToSave = createUserDTO.password;
    } else {
      passwordToSave = TemporaryPassword.generate().toString();
      isTemporary = true;
    }

    // ✅ REGRA 4: Persistir no repositório
    const savedUser = await this.userRepository.create(user, passwordToSave);

    // ✅ Limpar cache de lista
    await this._invalidateListCache();

    logger.info(
      { userId: savedUser.id, role: savedUser.role, autoGenerated: isTemporary },
      'Usuário criado com sucesso.'
    );

    return {
      user: savedUser,
      temporaryPassword: isTemporary ? passwordToSave : null, // Só retorna se foi gerada pelo sistema
    };
  }

  async _invalidateListCache() {
    await CacheService.delPattern('users:list:*');
  }
}

module.exports = CreateUserUseCase;